### ISSUE TITLE
Policy generator does not work with rails 3.0.17

### ISSUE THREAD

**Issue by trekdemo** [varvet/pundit#2]
rails 3.0.17
thor 0.14.6
pundit 0.1.0

```
$ bundle exec rails g pundit:policy workflow_template
      create  app/policies/workflow_template_policy.rb
(erb):1:in `template': undefined method `module_namespacing' for #<Pundit::Generators::PolicyGenerator:0x106ad6108> (NoMethodError)
        from (eval):1:in `template'
        from /Users/trek/dev/some_project/.bundle/gems/pundit-0.1.0/lib/generators/pundit/policy/policy_generator.rb:7:in `create_policy'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `invoke_all'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/shell.rb:14:in `map'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/core_ext/ordered_hash.rb:75:in `each'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `invoke_all'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
        from /Users/trek/dev/some_project/.bundle/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from /Users/trek/dev/some_project/.bundle/gems/railties-3.0.17/lib/rails/generators.rb:163:in `invoke'
        from /Users/trek/dev/some_project/.bundle/gems/railties-3.0.17/lib/rails/commands/generate.rb:10
        from /Users/trek/dev/some_project/.bundle/gems/polyglot-0.3.1/lib/polyglot.rb:64:in `polyglot_original_require'
        from /Users/trek/dev/some_project/.bundle/gems/polyglot-0.3.1/lib/polyglot.rb:64:in `require'
        from /Users/trek/dev/some_project/.bundle/gems/activesupport-3.0.17/lib/active_support/dependencies.rb:242:in `require'
        from /Users/trek/dev/some_project/.bundle/gems/activesupport-3.0.17/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/trek/dev/some_project/.bundle/gems/activesupport-3.0.17/lib/active_support/dependencies.rb:597:in `new_constants_in'
        from /Users/trek/dev/some_project/.bundle/gems/activesupport-3.0.17/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/trek/dev/some_project/.bundle/gems/activesupport-3.0.17/lib/active_support/dependencies.rb:242:in `require'
        from /Users/trek/dev/some_project/.bundle/gems/railties-3.0.17/lib/rails/commands.rb:17
        from script/rails:6:in `require'
        from script/rails:6
```
